In [2]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import warnings

warnings.filterwarnings("ignore")

In [3]:
model_df = pd.read_csv("../EDA/final_model.csv")

In [14]:
X = model_df.drop(['Runs', 'Ground', 'Start Date'], axis=1)
y = model_df['Runs']

In [15]:
X.head()

,Pos,Inns,NotOut,Rolling5,Rolling10,Opposition_v Australia,Opposition_v Bangladesh,Opposition_v England,Opposition_v Ireland,Opposition_v Netherlands,Opposition_v New Zealand,Opposition_v Pakistan,Opposition_v South Africa,Opposition_v Sri Lanka,Opposition_v U.A.E.,Opposition_v West Indies,Opposition_v Zimbabwe
0,2,2,0,12.000000,12.000000,0,0,0,0,0,0,0,0,1,0,0,0
1,1,1,0,24.500000,24.500000,0,0,0,0,0,0,0,0,1,0,0,0
2,1,1,0,24.666667,24.666667,0,0,0,0,0,0,0,0,1,0,0,0
3,1,2,0,32.000000,32.000000,0,0,0,0,0,0,0,0,1,0,0,0
4,7,1,1,31.800000,31.800000,0,0,0,0,0,0,0,0,1,0,0,0

# Train-test split

In [28]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, shuffle=False)

# Feature Scaling

In [31]:
scaler = StandardScaler()
X_train_scaled = pd.DataFrame(scaler.fit_transform(X_train), columns=X_train.columns, index=X_train.index)
X_test_scaled = pd.DataFrame(scaler.transform(X_test), columns=X_test.columns, index=X_test.index)

In [32]:
X_test_scaled

,Pos,Inns,NotOut,Rolling5,Rolling10,Opposition_v Australia,Opposition_v Bangladesh,Opposition_v England,Opposition_v Ireland,Opposition_v Netherlands,Opposition_v New Zealand,Opposition_v Pakistan,Opposition_v South Africa,Opposition_v Sri Lanka,Opposition_v U.A.E.,Opposition_v West Indies,Opposition_v Zimbabwe
238,-0.332478,0.880976,-0.442696,-0.057814,-0.201389,2.294157,-0.230429,-0.379777,-0.092057,-0.064957,-0.350202,-0.240370,-0.342594,-0.482867,-0.064957,-0.435890,-0.160817
239,-0.332478,0.880976,-0.442696,-0.607115,-0.773408,2.294157,-0.230429,-0.379777,-0.092057,-0.064957,-0.350202,-0.240370,-0.342594,-0.482867,-0.064957,-0.435890,-0.160817
240,-0.332478,-1.135104,-0.442696,-0.607115,-0.250595,2.294157,-0.230429,-0.379777,-0.092057,-0.064957,-0.350202,-0.240370,-0.342594,-0.482867,-0.064957,-0.435890,-0.160817
241,-0.332478,-1.135104,-0.442696,-0.491473,0.136902,-0.435890,-0.230429,2.633122,-0.092057,-0.064957,-0.350202,-0.240370,-0.342594,-0.482867,-0.064957,-0.435890,-0.160817
242,-0.332478,-1.135104,-0.442696,-0.096362,-0.041469,-0.435890,-0.230429,2.633122,-0.092057,-0.064957,-0.350202,-0.240370,-0.342594,-0.482867,-0.064957,-0.435890,-0.160817
243,-0.332478,-1.135104,-0.442696,0.452939,0.266068,-0.435890,-0.230429,2.633122,-0.092057,-0.064957,-0.350202,-0.240370,-0.342594,-0.482867,-0.064957,-0.435890,-0.160817
244,-0.332478,0.880976,-0.442696,0.318023,-0.170635,-0.435890,-0.230429,-0.379777,-0.092057,-0.064957,-0.350202,-0.240370,2.918904,-0.482867,-0.064957,-0.435890,-0.160817
245,-0.332478,-1.135104,-0.442696,-0.048178,-0.404363,-0.435890,-0.230429,-0.379777,-0.092057,-0.064957,-0.350202,-0.240370,2.918904,-0.482867,-0.064957,-0.435890,-0.160817
246,-0.332478,0.880976,-0.442696,-0.655299,-0.718051,-0.435890,-0.230429,-0.379777,-0.092057,-0.064957,-0.350202,-0.240370,2.918904,-0.482867,-0.064957,-0.435890,-0.160817
247,-0.332478,0.880976,-0.442696,-0.568568,-0.410514,-0.435890,-0.230429,-0.379777,-0.092057,-0.064957,-0.350202,-0.240370,-0.342594,-0.482867,-0.064957,2.294157,-0.160817
248,-0.332478,-1.135104,-0.442696,-1.127505,-0.416665,-0.435890,-0.230429,-0.379777,-0.092057,-0.064957,-0.350202,-0.240370,-0.342594,-0.482867,-0.064957,2.294157,-0.160817
249,-0.332478,-1.135104,-0.442696,-1.021500,-0.435117,-0.435890,-0.230429,-0.379777,-0.092057,-0.064957,-0.350202,-0.240370,-0.342594,-0.482867,-0.064957,2.294157,-0.160817
250,-0.332478,0.880976,-0.442696,-1.512980,-0.982533,-0.435890,-0.230429,2.633122,-0.092057,-0.064957,-0.350202,-0.240370,-0.342594,-0.482867,-0.064957,-0.435890,-0.160817
251,-0.332478,0.880976,-0.442696,-1.358790,-1.271618,-0.435890,-0.230429,2.633122,-0.092057,-0.064957,-0.350202,-0.240370,-0.342594,-0.482867,-0.064957,-0.435890,-0.160817
252,-0.332478,-1.135104,-0.442696,-1.821359,-1.511497,-0.435890,4.339739,-0.379777,-0.092057,-0.064957,-0.350202,-0.240370,-0.342594,-0.482867,-0.064957,-0.435890,-0.160817
253,-3.061089,0.880976,-0.442696,-1.811722,-1.862089,-0.435890,4.339739,-0.379777,-0.092057,-0.064957,-0.350202,-0.240370,-0.342594,-0.482867,-0.064957,-0.435890,-0.160817
254,-0.332478,-1.135104,-0.442696,-1.937001,-1.874391,-0.435890,4.339739,-0.379777,-0.092057,-0.064957,-0.350202,-0.240370,-0.342594,-0.482867,-0.064957,-0.435890,-0.160817
255,-0.332478,-1.135104,-0.442696,-0.848037,-1.493045,-0.435890,-0.230429,-0.379777,-0.092057,-0.064957,-0.350202,-0.240370,-0.342594,2.070963,-0.064957,-0.435890,-0.160817
256,-0.332478,0.880976,-0.442696,0.086738,-0.798011,-0.435890,-0.230429,-0.379777,-0.092057,-0.064957,-0.350202,-0.240370,-0.342594,2.070963,-0.064957,-0.435890,-0.160817
257,-0.332478,-1.135104,2.258886,-0.038541,-1.173206,-0.435890,-0.230429,-0.379777,-0.092057,-0.064957,-0.350202,-0.240370,-0.342594,2.070963,-0.064957,-0.435890,-0.160817
258,-0.332478,-1.135104,-0.442696,1.474446,-0.201389,-0.435890,-0.230429,-0.379777,-0.092057,-0.064957,2.855494,-0.240370,-0.342594,-0.482867,-0.064957,-0.435890,-0.160817
259,-0.332478,0.880976,-0.442696,1.503356,-0.262896,-0.435890,-0.230429,-0.379777,-0.092057,-0.064957,2.855494,-0.240370,-0.342594,-0.482867,-0.064957,-0.435890,-0.160817
260,-0.332478,-1.135104,-0.442696,0.520397,-0.195238,-0.435890,-0.230429,-0.379777,-0.092057,-0.064957,2.855494,-0.240370,-0.342594,-0.482867,-0.064957,-0.435890,-0.160817
261,-0.332478,0.880976,-0.442696,-0.221641,-0.072223,2.294157,-0.230429,-0.379777,-0.092057,-0.064957,-0.350202,-0.240370,-0.342594,-0.482867,-0.064957,-0.435890,-0.160817
262,-0.332478,-1.135104,-0.442696,-0.221641,-0.152183,2.294157,-0.230429,-0.379777,-0.092057,-0.064957,-0.350202,-0.240370,-0.342594,-0.482867,-0.064957,-0.435890,-0.160817
263,-0.332478,0.880976,-0.442696,-1.522616,-0.016866,2.294157,-0.230429,-0.379777,-0.092057,-0.064957,-0.350202,-0.240370,-0.342594,-0.482867,-0.064957,-0.435890,-0.160817
264,-0.332478,-1.135104,-0.442696,-1.079321,0.284520,-0.435890,-0.230429,-0.379777,-0.092057,-0.064957,-0.350202,4.160251,-0.342594,-0.482867,-0.064957,-0.435890,-0.160817
265,-0.332478,-1.135104,2.258886,-1.146779,-0.385911,-0.435890,-0.230429,-0.379777,-0.092057,-0.064957,-0.350202,4.160251,-0.342594,-0.482867,-0.064957,-0.435890,-0.160817
266,-0.332478,-1.135104,-0.442696,-0.318009,-0.330554,-0.435890,-0.230429,-0.379777,-0.092057,-0.064957,-0.350202,-0.240370,-0.342594,2.070963,-0.064957,-0.435890,-0.160817
267,-0.332478,0.880976,-0.442696,-0.327646,-0.336705,2.294157,-0.230429,-0.379777,-0.092057,-0.064957,-0.350202,-0.240370,-0.342594,-0.482867,-0.064957,-0.435890,-0.160817
268,-0.332478,0.880976,-0.442696,-0.086725,-1.013287,2.294157,-0.230429,-0.379777,-0.092057,-0.064957,-0.350202,-0.240370,-0.342594,-0.482867,-0.064957,-0.435890,-0.160817
269,-0.332478,0.880976,2.258886,0.212018,-0.539679,-0.435890,-0.230429,-0.379777,-0.092057,-0.064957,-0.350202,-0.240370,-0.342594,-0.482867,-0.064957,-0.435890,-0.160817
270,-0.332478,0.880976,-0.442696,0.703497,-0.269047,-0.435890,-0.230429,-0.379777,-0.092057,-0.064957,-0.350202,4.160251,-0.342594,-0.482867,-0.064957,-0.435890,-0.160817
271,-0.332478,0.880976,2.258886,-0.318009,-0.392062,-0.435890,4.339739,-0.379777,-0.092057,-0.064957,-0.350202,-0.240370,-0.342594,-0.482867,-0.064957,-0.435890,-0.160817
272,-0.332478,0.880976,-0.442696,0.645676,0.216862,-0.435890,-0.230429,-0.379777,-0.092057,-0.064957,2.855494,-0.240370,-0.342594,-0.482867,-0.064957,-0.435890,-0.160817
273,-0.332478,-1.135104,-0.442696,1.021513,0.610509,-0.435890,-0.230429,2.633122,-0.092057,-0.064957,-0.350202,-0.240370,-0.342594,-0.482867,-0.064957,-0.435890,-0.160817
274,-0.332478,-1.135104,-0.442696,0.202381,0.278369,-0.435890,-0.230429,-0.379777,-0.092057,-0.064957,-0.350202,-0.240370,-0.342594,2.070963,-0.064957,-0.435890,-0.160817
275,-0.332478,-1.135104,2.258886,0.520397,0.795032,-0.435890,-0.230429,-0.379777,-0.092057,-0.064957,-0.350202,-0.240370,2.918904,-0.482867,-0.064957,-0.435890,-0.160817
276,-0.332478,-1.135104,-0.442696,1.339530,0.665866,-0.435890,-0.230429,-0.379777,-0.092057,15.394804,-0.350202,-0.240370,-0.342594,-0.482867,-0.064957,-0.435890,-0.160817
277,-0.332478,-1.135104,-0.442696,0.838413,0.961102,-0.435890,-0.230429,-0.379777,-0.092057,-0.064957,2.855494,-0.240370,-0.342594,-0.482867,-0.064957,-0.435890,-0.160817
278,-0.332478,-1.135104,-0.442696,1.050424,1.336297,2.294157,-0.230429,-0.379777,-0.092057,-0.064957,-0.350202,-0.240370,-0.342594,-0.482867,-0.064957,-0.435890,-0.160817
279,-0.332478,0.880976,-0.442696,1.570814,1.145624,-0.435890,-0.230429,-0.379777,-0.092057,-0.064957,-0.350202,-0.240370,-0.342594,2.070963,-0.064957,-0.435890,-0.160817
280,-0.332478,0.880976,-0.442696,0.954055,0.954951,-0.435890,-0.230429,-0.379777,-0.092057,-0.064957,-0.350202,-0.240370,-0.342594,2.070963,-0.064957,-0.435890,-0.160817
281,-0.332478,0.880976,-0.442696,0.115649,0.942650,-0.435890,-0.230429,-0.379777,-0.092057,-0.064957,-0.350202,-0.240370,-0.342594,2.070963,-0.064957,-0.435890,-0.160817
282,-0.332478,0.880976,-0.442696,-0.183094,0.432138,-0.435890,-0.230429,2.633122,-0.092057,-0.064957,-0.350202,-0.240370,-0.342594,-0.482867,-0.064957,-0.435890,-0.160817
283,-0.332478,-1.135104,-0.442696,-1.262421,-0.121429,-0.435890,-0.230429,2.633122,-0.092057,-0.064957,-0.350202,-0.240370,-0.342594,-0.482867,-0.064957,-0.435890,-0.160817
284,-0.332478,0.880976,-0.442696,-1.281695,0.198410,-0.435890,4.339739,-0.379777,-0.092057,-0.064957,-0.350202,-0.240370,-0.342594,-0.482867,-0.064957,-0.435890,-0.160817
285,-0.332478,0.880976,2.258886,-1.300969,-0.207539,-0.435890,-0.230429,-0.379777,-0.092057,-0.064957,-0.350202,4.160251,-0.342594,-0.482867,-0.064957,-0.435890,-0.160817
286,-0.332478,-1.135104,-0.442696,-0.472199,-0.213690,-0.435890,-0.230429,-0.379777,-0.092057,-0.064957,2.855494,-0.240370,-0.342594,-0.482867,-0.064957,-0.435890,-0.160817
287,-0.332478,0.880976,-0.442696,-0.558931,-0.459720,2.294157,-0.230429,-0.379777,-0.092057,-0.064957,-0.350202,-0.240370,-0.342594,-0.482867,-0.064957,-0.435890,-0.160817
288,-0.332478,0.880976,-0.442696,0.202381,-0.662694,-0.435890,-0.230429,-0.379777,-0.092057,-0.064957,2.855494,-0.240370,-0.342594,-0.482867,-0.064957,-0.435890,-0.160817
289,-0.332478,-1.135104,-0.442696,-0.289099,-0.988684,2.294157,-0.230429,-0.379777,-0.092057,-0.064957,-0.350202,-0.240370,-0.342594,-0.482867,-0.064957,-0.435890,-0.160817
290,-0.332478,-1.135104,-0.442696,-0.501110,-1.136302,2.294157,-0.230429,-0.379777,-0.092057,-0.064957,-0.350202,-0.240370,-0.342594,-0.482867,-0.064957,-0.435890,-0.160817
291,-0.332478,0.880976,2.258886,-1.464795,-1.222412,2.294157,-0.230429,-0.379777,-0.092057,-0.064957,-0.350202,-0.240370,-0.342594,-0.482867,-0.064957,-0.435890,-0.160817
292,-0.332478,-1.135104,-0.442696,-0.857673,-0.890272,-0.435890,-0.230429,-0.379777,-0.092057,-0.064957,-0.350202,-0.240370,2.918904,-0.482867,-0.064957,-0.435890,-0.160817
293,-0.332478,-1.135104,-0.442696,-0.366194,-0.090675,-0.435890,-0.230429,-0.379777,-0.092057,-0.064957,-0.350202,-0.240370,2.918904,-0.482867,-0.064957,-0.435890,-0.160817
294,-0.332478,0.880976,2.258886,0.607129,0.216862,-0.435890,-0.230429,-0.379777,-0.092057,-0.064957,-0.350202,-0.240370,2.918904,-0.482867,-0.064957,-0.435890,-0.160817
295,-0.332478,0.880976,-0.442696,1.233524,0.481344,-0.435890,-0.230429,-0.379777,-0.092057,-0.064957,2.855494,-0.240370,-0.342594,-0.482867,-0.064957,-0.435890,-0.160817
296,-0.332478,-1.135104,-0.442696,2.129752,0.438289,-0.435890,-0.230429,-0.379777,-0.092057,-0.064957,2.855494,-0.240370,-0.342594,-0.482867,-0.064957,-0.435890,-0.160817
297,-0.332478,0.880976,-0.442696,1.638272,0.512098,-0.435890,-0.230429,-0.379777,-0.092057,-0.064957,2.855494,-0.240370,-0.342594,-0.482867,-0.064957,-0.435890,-0.160817

In [33]:
model = LinearRegression()

In [34]:
model.fit(X_train, y_train)

LinearRegression()

In [35]:
y_pred = model.predict(X_test)

In [36]:
y_pred

array([ 47.26092801,  45.71867535,  46.84932121,  36.82803429,
        37.55826516,  38.93052228,  46.27612582,  46.13744679,
        43.84298727,  51.84014513,  51.43560521,  51.65041992,
        33.12958877,  33.27348858,  43.75970961,  57.46136825,
        43.27917826,  41.6559768 ,  43.30696119,  82.75300935,
        51.01778856,  50.24546695,  48.98166822,  46.99363339,
        47.73684757,  44.24729514,  34.78791671,  73.37323507,
        43.53654077,  46.596963  ,  46.67726083, 105.99850313,
        37.4497629 ,  86.05976396,  48.71982528,  40.36771333,
        45.04069332,  87.28464319,  31.75791963,  50.40492909,
        51.41366492,  47.72967872,  46.28828826,  44.48758943,
        36.88260634,  35.01344772,  45.21812343,  72.36356616,
        46.84730712,  46.02333198,  47.20657824,  47.05493964,
        46.50670869,  82.75655752,  44.09415776,  45.65904482,
        86.30387812,  50.14683593,  52.83020331,  51.03208868])

In [37]:
MAE = mean_absolute_error(y_test, y_pred)
MSE = mean_squared_error(y_test, y_pred)
RMSE = mean_squared_error(y_test, y_pred) ** 0.5
R2 = r2_score(y_test, y_pred)

n = X_test.shape[0]
p = X_test.shape[1]

adjusted_r2 = (1 - ((1 - R2) * (n - 1)) // (n - p - 1))

In [38]:
print("MAE: ", MAE)
print("MSE: ", MSE)
print("RMSE: ", RMSE)
print("R2: ", R2)
print("adjusted_r2: ", adjusted_r2)

MAE:  35.345737401270554
MSE:  1610.0506554536707
RMSE:  40.125436514182255
R2:  0.14451786041243464
adjusted_r2:  0.0

In [42]:
y_train

0      37
1      25
2      54
3      31
4       2
       ..
233    78
234    89
235    51
236    15
237     9
Name: Runs, Length: 238, dtype: int64

# Training using Scaled df

In [43]:
scaled_model = LinearRegression()
scaled_model.fit(X_train_scaled, y_train)

LinearRegression()

In [45]:
y_pred_scaled = scaled_model.predict(X_test_scaled)
y_pred_scaled

array([ 47.26092801,  45.71867535,  46.84932121,  36.82803429,
        37.55826516,  38.93052228,  46.27612582,  46.13744679,
        43.84298727,  51.84014513,  51.43560521,  51.65041992,
        33.12958877,  33.27348858,  43.75970961,  57.46136825,
        43.27917826,  41.6559768 ,  43.30696119,  82.75300935,
        51.01778856,  50.24546695,  48.98166822,  46.99363339,
        47.73684757,  44.24729514,  34.78791671,  73.37323507,
        43.53654077,  46.596963  ,  46.67726083, 105.99850313,
        37.4497629 ,  86.05976396,  48.71982528,  40.36771333,
        45.04069332,  87.28464319,  31.75791963,  50.40492909,
        51.41366492,  47.72967872,  46.28828826,  44.48758943,
        36.88260634,  35.01344772,  45.21812343,  72.36356616,
        46.84730712,  46.02333198,  47.20657824,  47.05493964,
        46.50670869,  82.75655752,  44.09415776,  45.65904482,
        86.30387812,  50.14683593,  52.83020331,  51.03208868])

In [47]:
MAE_scaled = mean_absolute_error(y_test, y_pred_scaled)
MSE_scaled = mean_squared_error(y_test, y_pred_scaled)
RMSE_scaled = mean_squared_error(y_test, y_pred_scaled) ** 0.5
R2_scaled = r2_score(y_test, y_pred_scaled)

n_scaled = X_test_scaled.shape[0]
p_scaled = X_test_scaled.shape[1]

adjusted_r2_scaled = (1 - ((1 - R2) * (n_scaled - 1)) // (n_scaled - p_scaled - 1))

In [48]:
print("MAE: ", MAE_scaled)
print("MSE: ", MSE_scaled)
print("RMSE: ", RMSE_scaled)
print("R2: ", R2_scaled)
print("adjusted_r2: ", adjusted_r2_scaled)

MAE:  35.34573740127054
MSE:  1610.0506554536705
RMSE:  40.125436514182255
R2:  0.14451786041243475
adjusted_r2:  0.0